name: Build and Deploy Docker Image

# 允许手动触发工作流
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 从 GitHub Secrets 获取 Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # 从 GitHub Secrets 获取 Docker Hub 密码

      # 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t your-dockerhub-username/your-image-name:${{ github.sha }} .

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push your-dockerhub-username/your-image-name:${{ github.sha }}

      # 部署到服务器（生产环境）
      - name: Deploy to server
        run: |
          echo "Deploying to production server"
          # 这里是部署到生产服务器的脚本，比如：
          # ssh user@production-server "cd /path/to/deploy && git pull && npm install && pm2 restart app"
