name: Build and Deploy Frontend to Alibaba Cloud ACR

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 构建项目
      - name: Build project
        run: pnpm run build

      # 登录到阿里云镜像仓库
      - name: Log in to Alibaba Cloud ACR
        run: |
          echo "${{ secrets.ALIYUN_ACR_PASSWORD }}" | docker login --username ${{ secrets.ALIYUN_ACR_USERNAME }} --password-stdin ${{ secrets.ALIYUN_ACR_REGISTRY }}

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ALIYUN_ACR_REGISTRY }}:${{ github.sha }} .

      # 推送 Docker 镜像到阿里云镜像仓库
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ALIYUN_ACR_REGISTRY }}:${{ github.sha }}

      # 部署到服务器（通过 SSH 拉取镜像并运行容器）
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # 登录到阿里云镜像仓库
            echo "${{ secrets.ALIYUN_ACR_PASSWORD }}" | docker login --username ${{ secrets.ALIYUN_ACR_USERNAME }} --password-stdin ${{ secrets.ALIYUN_ACR_REGISTRY }}

            # 拉取最新的镜像
            docker pull ${{ secrets.ALIYUN_ACR_REGISTRY }}:${{ github.sha }}

            # 停止并删除旧容器（如果存在）
            if docker ps -a --filter "name=zjzc" | grep -q zjzc; then
              docker stop zjzc || true
              docker rm zjzc || true
            fi

            # 启动新容器
            docker run -d --name zjzc -p 8080:8080 ${{ secrets.ALIYUN_ACR_REGISTRY }}:${{ github.sha }}