name: Build and Deploy Frontend

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 运行测试
      - name: Run tests
        run: pnpm dev

      # 构建项目
      - name: Build project
        run: pnpm run build

      # 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t your-dockerhub-username/frontend-app:${{ github.sha }} .

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image
        run: docker push your-dockerhub-username/frontend-app:${{ github.sha }}

      # 部署到服务器（假设使用 SSH）
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull your-dockerhub-username/frontend-app:${{ github.sha }}
            docker stop frontend-app || true
            docker rm frontend-app || true
            docker run -d --name frontend-app -p 80:80 your-dockerhub-username/frontend-app:${{ github.sha }}